name: CI

on:
    push:
        branches: ["main"]
    # Enable run the workflow manually
    workflow_dispatch:

jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set Target Branch
              run: echo "TARGET_BRANCH=main" >> $GITHUB_ENV

            - name: Build Docker image
              run: echo "${GITHUB_SHA}" && docker build -f Dockerfile -t ghcr.io/${{ github.repository }}/smart_console_adapter:${{ env.TARGET_BRANCH }} --build-arg GIT_COMMIT_HASH="${GITHUB_SHA}" .

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Push Docker image
              run: docker push ghcr.io/${{ github.repository }}/smart_console_adapter:${{ env.TARGET_BRANCH }}
